### ISSUE TITLE
failed to build docker file on win

### ISSUE THREAD

**Issue by stolltho** [meowcat/MSNovelist#1]
Hi there,

I already struggle to build msnovelist (see below). Any idea? I am not a specialist in this, don't even know where to look for this dockerfile. 

Cheers,
Thomas

PS N:\> docker build . -t msnovelist
[+] Building 0.1s (2/2) FINISHED
 => [internal] load build definition from Dockerfile                                                      0.1s
 => => transferring dockerfile: 2B                                                                        0.1s
 => CANCELED [internal] load .dockerignore                                                                0.1s
 => => transferring context:                                                                              0.0s
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount865313132/Dockerfile: no such file or directory

**Comment by meowcat** [comment]
You are in N:, is this where your Git repository is? You need to cd into the repository and run the build command there.

**Comment by stolltho** [comment]
Sorry, ignore this. Mixed up docker pull and docker build

**Comment by meowcat** [comment]
Super, good luck and don't hesitate to come back with further questions!
(For now I haven't pushed it to docker registry.)
