### ISSUE TITLE
Error when loading confidence SVMs

### ISSUE THREAD

**Issue by stolltho** [meowcat/MSNovelist#3]
Hi, I frequently get now this error below. Cheers, Thomas

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\admin> docker run -v C:\temp\MSNovelist_data\MF:/msnovelist-data msnovelist predict.sh 257_CE10.mgf
INFO  06:54:44 - Sirius Workspace Successfull initialized at: /root/.sirius-4.4
INFO  06:54:44 - You run SIRIUS 4.4.29
INFO  06:54:45 - Sirius was compiled with the following ILP solvers: GLPK-v1.7.0 (included), Gurobi-v8.1.0, CPLEX-v12.7.1, COIN-OR-v1.17.3
INFO  06:54:45 - Treebuilder priorities are: [CLP, CPLEX, GUROBI, GLPK]
INFO  06:54:45 - CPU check done. 4 cores that handle 8 threads were found.
INFO  06:54:45 - Bug reporter initialized.
INFO  06:54:45 - Web API initialized.
INFO  06:54:45 - Running with following arguments: [--log=WARNING, -i, /msnovelist-data/257_CE10.mgf, -o, /msnovelist-data/sirius-1627368883, formula, -p, qtof, structure, -d, ALL_BUT_INSILICO]
INFO  06:54:45 - Job manager successful initialized with 4 CPU thread(s) and 3 IO thread(s).
**SEVERE06:54:55 - Error when loading confidence SVMs. Confidence SCore will not be available!**

**Comment by meowcat** [comment]
I tried some things out and I only got this error when I have a negative-mode spectrum. Is this the case? In theory SIRIUS 4.4.29 itself should still handle negative mode fine, so I'm not sure why this happens - however MSNovelist will not work with negative mode data yet.

**Comment by stolltho** [comment]
Thanks for clarification. It is indeed neg mode data. Tested w/ pos mode data and everything ran fine. Looking forward for MSNovelist to work w/ neg mode data.
