### ISSUE TITLE
ValueError: No objects to concatenate

### ISSUE THREAD

**Issue by dlrudgks1022** [meowcat/MSNovelist#6]
PS C:\PIW> docker run --init -v C:\PIW:/msnovelist-data stravsm/msnovelist predict.sh 377.mgf
INFO  05:58:55 - Sirius Workspace Successfull initialized at: /root/.sirius-4.4
INFO  05:58:55 - You run SIRIUS 4.4.29
INFO  05:58:55 - Sirius was compiled with the following ILP solvers: GLPK-v1.7.0 (included), Gurobi-v8.1.0, CPLEX-v12.7.1, COIN-OR-v1.17.3
INFO  05:58:55 - Treebuilder priorities are: [CLP, CPLEX, GUROBI, GLPK]
INFO  05:58:55 - CPU check done. 12 cores that handle 24 threads were found.
INFO  05:58:55 - Bug reporter initialized.
INFO  05:58:55 - Web API initialized.
INFO  05:58:55 - Running with following arguments: [--log=WARNING, -i, /msnovelist-data/377.mgf, -o, /msnovelist-data/sirius-1662098334, formula, -p, qtof, structure, -d, ALL_BUT_INSILICO]
INFO  05:58:55 - Job manager successful initialized with 12 CPU thread(s) and 3 IO thread(s).
WARNING05:58:55 - Path "/msnovelist-data/377.mgf" does not exist and will be skipped
INFO  05:58:56 - Workflow has been finished!
INFO  05:58:56 - Executing Postprocessing...
INFO  05:58:56 - Writing summary files...
INFO  05:58:56 - Project-Space summaries successfully written!
INFO  05:58:56 - CLI shut down hook: SIRIUS is cleaning up threads and shuts down...

Please cite the following publications when using our tool:

When using the SIRIUS Software please cite the following paper:

Kai Dührkop, Markus Fleischauer, Marcus Ludwig, Alexander A. Aksenov, Alexey V. Melnik, Marvin Meusel, Pieter C. Dorrestein, Juho Rousu and Sebastian Böcker
SIRIUS4: a rapid tool for turning tandem mass spectra into metabolite structure information
Nat Methods, 16, 2019.  https://doi.org/10.1038/s41592-019-0344-8

Depending on the tools you have used please also cite:

Kai Dührkop, Louis-Félix Nothias, Markus Fleischauer, Marcus Ludwig, Martin A. Hoffmann, Juho Rousu, Pieter C. Dorrestein,  Sebastian Böcker
Classes for the masses: Systematic classification of unknowns using fragmentation spectra
bioRxiv, 2020.  https://doi.org/10.1101/2020.04.17.046672
(Cite if you are using: CANOPUS)

Yannick Djoumbou Feunang, Roman Eisner, Craig Knox, Leonid Chepelev, Janna Hastings, Gareth Owen, Eoin Fahy, Christoph Steinbeck, Shankar Subramanian, Evan Bolton, Russell Greiner, David S. Wishart
ClassyFire: automated chemical classification with a comprehensive, computable taxonomy
J Cheminf, 8, 2016.  https://doi.org/10.1186/s13321-016-0174-y
(Cite if you are using: CANOPUS)

Kai Dührkop, Huibin Shen, Marvin Meusel, Juho Rousu and Sebastian Böcker
Searching molecular structure databases with tandem mass spectra using CSI:FingerID
Proc Natl Acad Sci U S A, 112, 2015.  https://doi.org/10.1073/pnas.1509788112
(Cite if you are using: CSI:FingerID)

Sebastian Böcker and Kai Dührkop
Fragmentation trees reloaded
J Cheminform, 8, 2016.  https://doi.org/10.1186/s13321-016-0116-8
(Cite if you are using: Fragmentation Trees)

Sebastian Böcker, Matthias Letzel, Zsuzsanna Lipták and Anton Pervukhin
SIRIUS: Decomposing isotope patterns for metabolite identification
Bioinformatics, 25, 2009.  https://doi.org/10.1093/bioinformatics/btn603
(Cite if you are using: Isotope Pattern analysis)

Marcus Ludwig, Louis-Félix Nothias, Kai Dührkop, Irina Koester, Markus Fleischauer, Martin A. Hoffmann, Daniel Petras, Fernando Vargas, Mustafa Morsy, Lihini Aluwihare, Pieter C. Dorrestein, Sebastian Böcker
ZODIAC: database-independent molecular formula annotation using Gibbs sampling reveals unknown small molecules
bioRxiv, 2019.  https://doi.org/10.1101/842740
(Cite if you are using: ZODIAC)

02-Sep-22 05:58:59 - decode_applied startup
100%|██████████| 127/127 [00:00<00:00, 81449.02it/s]
02-Sep-22 05:59:00 - Not in lookup database: Counter({'f': 127}) entries
02-Sep-22 05:59:02 - Sampler fp_sampling.cv_sampler_direct settings loading
02-Sep-22 05:59:02 - Sampler fp_sampling.cv_sampler_direct settings loaded
02-Sep-22 05:59:02 - Selecting fingerprint fingerprint
02-Sep-22 05:59:03 - Loading layer encoder weights
02-Sep-22 05:59:03 - Loaded
02-Sep-22 05:59:03 - Loading layer hydrogen_estimator weights
02-Sep-22 05:59:03 - Loaded
02-Sep-22 05:59:03 - Loading layer tokens_y weights
02-Sep-22 05:59:03 - Loaded
02-Sep-22 05:59:03 - Processing 0 queries
0it [00:00, ?it/s]
02-Sep-22 05:59:03 - Processing 0 queries - fingerprinting results
0it [00:00, ?it/s]
02-Sep-22 05:59:03 - Processing 0 queries - merging
Traceback (most recent call last):
  File "/msnovelist/decode_applied.py", line 271, in <module>
    results_processed = pd.concat(results_processed_)
  File "/opt/conda/envs/msnovelist-env/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 295, in concat
    sort=sort,
  File "/opt/conda/envs/msnovelist-env/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 342, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
PS C:\PIW>

**Comment by Jack-Hu-2001** [comment]
I'm having the same problem. Have you solverd this? Could you give ne some hints?

**Comment by Jack-Hu-2001** [comment]
solved, sorry for not palcing mgf file under the dataroot.
